swiftmailer:
    spool: {type: 'memory'}
    transport: gmail
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASS)%'
    host: smtp.gmail.com
    port: 465
    encryption: ssl
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
