sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_admin_emailCofnig:
    prefix: /admin
    resource: |
        alias: app.emailCofnig
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: app_admin_emailCofnig
        vars:
            all:
                subheader: admin_email_configuration.ui.emailCofnigs
            index:
                icon: 'file image outline'
    type: sylius.resource
