sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_admin_emailConfig:
    prefix: /admin
    resource: |
        alias: app.emailConfig
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: app_admin_emailConfig
        vars:
            all:
                subheader: app.ui.emailConfigs
            index:
                icon: 'inbox'
    type: sylius.resource
